repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.5.0' # latest from: https://github.com/pre-commit/pre-commit-hooks/releases
  hooks:
  - id: check-yaml
  - id: check-json
  - id: pretty-format-json
    args:
    - "--autofix"
    - "--indent=4"
    - "--no-sort-keys"
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: end-of-file-fixer
  - id: trailing-whitespace
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: detect-private-key
  - id: check-added-large-files
  - id: check-ast
  - id: check-byte-order-marker
  - id: check-builtin-literals
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: requirements-txt-fixer
  - id: sort-simple-yaml

- repo: https://github.com/PyCQA/bandit
  rev: '1.7.5' # Latest from: https://github.com/PyCQA/bandit/releases
  hooks:
  - id: bandit

- repo: https://github.com/psf/black
  rev: '23.10.1' # Latest from: https://github.com/psf/black/releases
  hooks:
  - id: black

- repo: https://github.com/bridgecrewio/checkov.git
  rev: '3.0.14' # Get the latest from: https://github.com/bridgecrewio/checkov/releases
  hooks:
  - id: checkov
    args: ["--quiet", "--skip-check", "CKV_TF_1"]
    additional_dependencies:
      - "cyclonedx-python-lib==5.2.0"
  - id: checkov_secrets
    additional_dependencies:
      - "cyclonedx-python-lib==5.2.0"
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.5 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
  hooks:
  - id: terraform_fmt
  - id: terraform_tflint
    args:
    - --args=--module
  - id: terraform_validate
  - id: terraform_docs
    args:
    - --hook-config=--path-to-file=README.md
    - --hook-config=--add-to-existing-file=true
    - --hook-config=--create-file-if-not-exist=true
